version: 2.1

aliases:
  filter-all: &filter-all
    filters:
      tags:
        only: /.*/
  filter-release: &filter-release
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v\d+\.\d+\.\d+$/

orbs:
  go-module: timakin/go-module@0.3.0
  go-crossbuild: izumin5210/go-crossbuild@0.1.1
  github-release: izumin5210/github-release@0.1.1
  homebrew: izumin5210/homebrew@0.1.3
  inline: izumin5210/inline@0.1.0

executors:
  default:
    docker:
    - image: circleci/golang:1.12
    environment:
    - GO111MODULE: "on"

workflows:
  version: 2
  main:
    jobs:
    - go-module/download:
        <<: *filter-all
        executor: default
        persist-to-workspace: true
        vendoring: true

    - inline/steps:
        executor: default
        context: reviewdog
        name: 'lint'
        steps:
        - run: make lint
        requires:
        - go-module/download

    - inline/steps:
        <<: *filter-all
        executor: default
        name: 'test'
        steps:
        - run: go test -v ./...
        requires:
        - go-module/download

    - go-crossbuild/build:
        <<: *filter-all
        executor: default
        packages: ./cmd/gex
        requires:
        - go-module/download

    - github-release/create:
        <<: *filter-release
        executor: default
        context: tool-releasing
        requires:
        - test
        - go-crossbuild/build

    - homebrew/update:
        <<: *filter-release
        executor: default
        context: tool-releasing
        requires:
        - github-release/create
