// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

//go:build tools
// +build tools

package tools

// tool dependencies
import (
	_ "github.com/gogo/protobuf/protoc-gen-gogofast"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"
	_ "github.com/volatiletech/sqlboiler"
	_ "github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/protoc-gen-gogofast github.com/gogo/protobuf/protoc-gen-gogofast
//go:generate go build -v -o=./bin/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
//go:generate go build -v -o=./bin/protoc-gen-swagger github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
//go:generate go build -v -o=./bin/sqlboiler github.com/volatiletech/sqlboiler
//go:generate go build -v -o=./bin/sqlboiler-psql github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql

