// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools
//gex:nobin

package tools

// tool dependencies
import (
	_ "github.com/gogo/protobuf/protoc-gen-gogofast"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
	//gex:bin
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"
	//gex:nobin
	_ "github.com/volatiletech/sqlboiler"
	//gex:nobin
	_ "github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/protoc-gen-swagger github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

